### ISSUE TITLE
錦明朝かなの半角英数字を使用

### ISSUE THREAD

**Issue by metasta** [metasta/asebi#2]
かな文字と全角の約物だけでなく、半角英数字にも錦明朝かなの文字を使用したい。

現在の作成手順ではCFFとnameのテーブルを置換するだけなので、グリフを更新してもグリフの字幅の情報が更新されない。そのためプロポーショナルなグリフは表示が崩れる。

どのテーブルをどう加工すべきかもう少し勉強したら挑戦してみる。

**Comment by jhsho** [comment]
你好 非常感謝您推出了舊明朝體 我們也在致力於製作ipamj明朝的舊字形 但由於不會otf特性 就擱淺了 希望您補全漢字(不包括簡體中文)  請您留下聯繫方式 我把我們做的舊字形發給你 希望您能收錄  直書敬上

**Comment by metasta** [comment]
@jhsho Thank you for your great offer! There's one point to confirm: 馬醉木明朝(asebi) contains IPAmj明朝's 舊字 glyphs, so it has to be licensed under IPA Font License Agreement v1.0. We cannot remain your glyphs' own license.
But if that's okay, please send me your glyphs (.CFF format is the best) to metasta@gmail.com! I'll try to include your glyphs into my 馬酔木明朝. 本当にありがとうございます！

**Comment by metasta** [comment]
ともあれ、この issue は v1.010 で解決したので閉めます。解決方法はプログラム本体をみれば分かるが、簡単にメモしておくと

v1.009 まで：
name と CFF を自作
残りは sammin のデータを使用

v1.010 から：
name と CFF を自作
sammin の cmap を使用
残りは otagi のデータを使用

**Comment by jhsho** [comment]
$B!VED(B $B3$El!WVagP(B?$B6&MQ(B OneDrive $B8D(B?$B0F!#<cMW\};k(B?$B0F!$@A0D0l2<2<LLE*O"7k!#(B


<https://1drv.ms/u/s!ApcouLt0sPmlg0TM8rs6A5GJO9vv>
[https://r1.res.office365.com/owa/prem/images/dc-generic_20.png]<https://1drv.ms/u/s!ApcouLt0sPmlg0TM8rs6A5GJO9vv>

ipamjm$BL@qs(B.7z<https://1drv.ms/u/s!ApcouLt0sPmlg0TM8rs6A5GJO9vv>



[cid:1b94fbea-84ef-47a7-b25d-f1b91ad20ff4]

[cid:43594dec-5ed6-4aad-bc49-52f45886be02]

ipamj$BL@qs0Y=$2~HG(B $B@AMQ(B7z$B2rTZ=L(B

________________________________
$B4s7o<T(B: Yoichiro MATSUMOTO <notifications@github.com>
$B4s7oF|4|(B: 2016$BG/(B5$B7n(B11$BF|(B $B>e8a(B 09:26:22
$BZ@7o<T(B: metasta/asebi
$BI{K\(B: jhsho; Mention
$B<g;](B: Re: [metasta/asebi] $B6SL@D+$+$J$NH>3Q1Q?t;z$r;HMQ(B (#2)


$B$H$b$"$l!"$3$N(B issue $B$O(B v1.010 $B$G2r7h$7$?$N$GJD$a$^$9!#2r7hJ}K!$O%W%m%0%i%`K\BN$r$_$l$PJ,$+$k$,!"4JC1$K%a%b$7$F$*$/$H(B

v1.009 $B$^$G!'(B
name $B$H(B CFF $B$r<+:n(B
$B;D$j$O(B sammin $B$N%G!<%?$r;HMQ(B

v1.010 $B$+$i!'(B
name $B$H(B CFF $B$r<+:n(B
sammin $B$N(B cmap $B$r;HMQ(B
$B;D$j$O(B otagi $B$N%G!<%?$r;HMQ(B

-
